# HandWritten Image detection

In [1]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np

In [2]:
(X_train, Y_train), (X_test, Y_test) = keras.datasets.mnist.load_data()

In [3]:
X_train.shape

(60000, 28, 28)

In [4]:
x_train_flattened = X_train.reshape(60000, 28*28)

In [5]:
x_test_flattened = X_test.reshape(len(X_test), 28*28)

In [6]:
###scaling

In [7]:
x_train_flattened = x_train_flattened / 255

In [8]:
### creating the model

### model with no hidden layers

In [9]:
### simple model with no hidden layers
model = keras.Sequential([
    keras.layers.Dense(10, input_shape = (784,), activation = 'sigmoid')
]) ## 10 is the size of the output neuron and 784 is the input

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(x_train_flattened, Y_train, epochs=30)

Epoch 1/30
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4653 - accuracy: 0.8784
Epoch 2/30
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3041 - accuracy: 0.9151
Epoch 3/30
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2832 - accuracy: 0.9204
Epoch 4/30
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2734 - accuracy: 0.9238
Epoch 5/30
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2666 - accuracy: 0.9257
Epoch 6/30
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2619 - accuracy: 0.9268
Epoch 7/30
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2582 - accuracy: 0.9277
Epoch 8/30
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2553 - accuracy: 0.9290
Epoch 9/30
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2531 - accuracy: 0.9300
Epoch 10/30
1875/1875 [==============================] - 4s 2ms/step - loss: 0.250

In [10]:
### testing on test dataset

In [11]:
x_test = x_test_flattened / 255

In [12]:
model.evaluate(x_test, Y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.2727 - accuracy: 0.9267


[0.27270883321762085, 0.9266999959945679]

In [13]:
y_predicts = model.predict(x_test)  ### gives output of the prediction of the input dataset

313/313 [==============================] - 1s 2ms/step


In [14]:
y_predicts_val = []
for i in y_predicts:
    y_predicts_val.append(np.argmax(i))

In [15]:
y_predicts_val[:7]    ### predicted values

[7, 2, 1, 0, 4, 1, 4]

In [16]:
Y_test[:7]    ### actual values

array([7, 2, 1, 0, 4, 1, 4], dtype=uint8)

In [17]:
### confusion matrix
cm = tf.math.confusion_matrix(labels=Y_test, predictions = y_predicts_val)
print(cm)

tf.Tensor(
[[ 956    0    0    2    1    8    9    3    1    0]
 [   0 1116    4    2    0    2    4    2    5    0]
 [   4    9  925   17    8    3   13    9   41    3]
 [   3    0   17  929    1   21    3   10   20    6]
 [   1    2    6    3  918    0   10    7    8   27]
 [   7    3    1   38    9  781   16    5   29    3]
 [   9    3    7    1    7   12  916    1    2    0]
 [   1    8   21    7    4    1    0  949    4   33]
 [   7    8    6   22    8   33   11   10  861    8]
 [   8    8    2   11   26    7    0   23    8  916]], shape=(10, 10), dtype=int32)


### model with 1 hidden layer

In [18]:

model1 = keras.Sequential([
    keras.layers.Dense(100, input_shape = (784,), activation = 'relu'),
    keras.layers.Dense(10, activation = tf.nn.sigmoid)
]) ## 10 is the size of the output neuron and 784 is the input

model1.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model1.fit(x_train_flattened, Y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.2892 - accuracy: 0.9202
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1302 - accuracy: 0.9616
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0933 - accuracy: 0.9727
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0716 - accuracy: 0.9789
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0585 - accuracy: 0.9823


In [19]:
### evaluating
model1.evaluate(x_test, Y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.0761 - accuracy: 0.9770


[0.07607213407754898, 0.9769999980926514]

### model with 2 hidden layers

In [20]:
model2 = keras.Sequential([
    keras.layers.Dense(50, input_shape = (784,), activation = 'relu'),
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model2.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model2.fit(x_train_flattened, Y_train, epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.3034 - accuracy: 0.9108
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1434 - accuracy: 0.9570
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1049 - accuracy: 0.9680
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0842 - accuracy: 0.9738
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0689 - accuracy: 0.9782


In [21]:
model2.evaluate(x_test, Y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.0993 - accuracy: 0.9686


[0.09928522258996964, 0.9685999751091003]

# Matrix excersize 

### excersize 1

In [22]:
revenue_in_usd = np.array([[200, 220, 250], [68, 79, 105], [110, 140, 180], [80, 85, 90]])
conversion_rate = 75

revenew_in_inr = revenue_in_usd * conversion_rate
revenew_in_inr

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

### excersize 2 

In [23]:
units_sold = np.array([[50, 60, 25], [10, 13, 5], [40, 70, 52]])
price_per_unit = np.array([20, 30, 15])

total_price_per_month = np.dot(price_per_unit, units_sold)
total_price_per_month

array([1900, 2640, 1430])

In [24]:
total_price_per_flower = np.dot(price_per_unit, units_sold.T)
total_price_per_flower

array([3175,  665, 3680])

# scalling


In [39]:
class min_max_scalling:
    def __init__(self, arr, new_min = 0, new_max = 1):
        self.new_min, self.new_max = new_min, new_max
        self.old_min, self.old_max = min(arr), max(arr)

        self.new_arr = []
        for i in range(len(arr)):
            old_val = arr[i]
            new_val = ((old_val - self.old_min) / (self.old_max - self.old_min) * (self.new_max - self.new_min)) + self.new_min
            self.new_arr.append(new_val)
        
        self.new_arr = np.array(self.new_arr)
    
    def fitting(self):
        return self.new_arr
    
    def descale(self, arr):
        ret = []
        for element in arr:
            out_scale = element - self.new_min
            out_scale = out_scale * (self.old_max - self.old_min)
            out_scale = out_scale / (self.new_max - self.new_min)
            out_scale = out_scale + self.old_min
            
            ret.append(out_scale)
        
        ret = np.array(ret)
        return ret

In [40]:
x = [128, 9, 0, 78, -90, -78]
cs = min_max_scalling(x)
arr = cs.fitting()
arr

array([1.        , 0.45412844, 0.41284404, 0.7706422 , 0.        ,
       0.05504587])

In [41]:
cs.descale([1.        , 0.45412844, 0.41284404, 0.7706422 , 0.        ,
       0.05504587])

array([ 1.28000000e+02,  8.99999992e+00,  7.20000003e-07,  7.79999996e+01,
       -9.00000000e+01, -7.80000003e+01])